require 'system_builder'
require 'system_builder/task'

def working_dir(name, type)
  "/var/tmp/system-builder/#{name}/#{type}"
end

SystemBuilder::Task.new(:simple_test) do
  SystemBuilder::DiskImage.new(working_dir("simple_test", :disk)).tap do |image|
    image.boot = SystemBuilder::DebianBoot.new(working_dir("simple_test", :boot)).tap do |boot|
      boot.mirror = "http://127.0.0.1:9999/debian"
    end
    
    image.boot.configure do |chroot|
      chroot.apt_install :sudo
    end
  end
end
